// Top 30 WOAH-listed diseases critical for Africa

export interface DiseaseSeed {
  code: string;
  nameEn: string;
  nameFr: string;
  namePt: string;
  nameAr: string;
  isWoahListed: boolean;
  affectedSpecies: string[]; // species codes
  isNotifiable: boolean;
  wahisCategory: string;
}

export const DISEASE_SEEDS: DiseaseSeed[] = [
  { code: 'FMD', nameEn: 'Foot and mouth disease', nameFr: 'Fièvre aphteuse', namePt: 'Febre aftosa', nameAr: 'الحمى القلاعية', isWoahListed: true, affectedSpecies: ['BOS-TAU', 'BOS-IND', 'OVI-ARI', 'CAP-HIR', 'SUS-DOM', 'SYN-CAF', 'BUB-BUB'], isNotifiable: true, wahisCategory: 'multiple_species' },
  { code: 'CBPP', nameEn: 'Contagious bovine pleuropneumonia', nameFr: 'Péripneumonie contagieuse bovine', namePt: 'Perineumonia contagiosa bovina', nameAr: 'الالتهاب الرئوي البلوري المعدي في الأبقار', isWoahListed: true, affectedSpecies: ['BOS-TAU', 'BOS-IND', 'BUB-BUB'], isNotifiable: true, wahisCategory: 'cattle' },
  { code: 'PPR', nameEn: 'Peste des petits ruminants', nameFr: 'Peste des petits ruminants', namePt: 'Peste dos pequenos ruminantes', nameAr: 'طاعون المجترات الصغيرة', isWoahListed: true, affectedSpecies: ['OVI-ARI', 'CAP-HIR'], isNotifiable: true, wahisCategory: 'small_ruminants' },
  { code: 'RVF', nameEn: 'Rift Valley fever', nameFr: 'Fièvre de la Vallée du Rift', namePt: 'Febre do Vale do Rift', nameAr: 'حمى الوادي المتصدع', isWoahListed: true, affectedSpecies: ['BOS-TAU', 'BOS-IND', 'OVI-ARI', 'CAP-HIR', 'CAM-DRO'], isNotifiable: true, wahisCategory: 'multiple_species' },
  { code: 'ASF', nameEn: 'African swine fever', nameFr: 'Peste porcine africaine', namePt: 'Peste suína africana', nameAr: 'حمى الخنازير الأفريقية', isWoahListed: true, affectedSpecies: ['SUS-DOM', 'PHA-AET'], isNotifiable: true, wahisCategory: 'swine' },
  { code: 'HPAI', nameEn: 'Highly pathogenic avian influenza', nameFr: 'Influenza aviaire hautement pathogène', namePt: 'Influenza aviária altamente patogénica', nameAr: 'إنفلونزا الطيور شديدة الإمراض', isWoahListed: true, affectedSpecies: ['GAL-DOM', 'ANA-PLA', 'ANS-DOM', 'MEL-GAL', 'NUM-MEL'], isNotifiable: true, wahisCategory: 'avian' },
  { code: 'LPAI', nameEn: 'Low pathogenic avian influenza', nameFr: 'Influenza aviaire faiblement pathogène', namePt: 'Influenza aviária de baixa patogenicidade', nameAr: 'إنفلونزا الطيور منخفضة الإمراض', isWoahListed: true, affectedSpecies: ['GAL-DOM', 'ANA-PLA', 'ANS-DOM'], isNotifiable: true, wahisCategory: 'avian' },
  { code: 'NCD', nameEn: 'Newcastle disease', nameFr: 'Maladie de Newcastle', namePt: 'Doença de Newcastle', nameAr: 'مرض نيوكاسل', isWoahListed: true, affectedSpecies: ['GAL-DOM', 'MEL-GAL', 'NUM-MEL', 'COL-LIV'], isNotifiable: true, wahisCategory: 'avian' },
  { code: 'LSD', nameEn: 'Lumpy skin disease', nameFr: 'Dermatose nodulaire contagieuse', namePt: 'Dermatose nodular contagiosa', nameAr: 'الجلد العقدي', isWoahListed: true, affectedSpecies: ['BOS-TAU', 'BOS-IND', 'BUB-BUB'], isNotifiable: true, wahisCategory: 'cattle' },
  { code: 'SGP', nameEn: 'Sheep pox and goat pox', nameFr: 'Clavelée et variole caprine', namePt: 'Varíola ovina e caprina', nameAr: 'جدري الأغنام والماعز', isWoahListed: true, affectedSpecies: ['OVI-ARI', 'CAP-HIR'], isNotifiable: true, wahisCategory: 'small_ruminants' },
  { code: 'RAB', nameEn: 'Rabies', nameFr: 'Rage', namePt: 'Raiva', nameAr: 'داء الكلب', isWoahListed: true, affectedSpecies: ['CAN-FAM', 'FEL-CAT', 'BOS-TAU', 'BOS-IND'], isNotifiable: true, wahisCategory: 'multiple_species' },
  { code: 'ANT', nameEn: 'Anthrax', nameFr: 'Fièvre charbonneuse', namePt: 'Carbúnculo hemático', nameAr: 'الجمرة الخبيثة', isWoahListed: true, affectedSpecies: ['BOS-TAU', 'BOS-IND', 'OVI-ARI', 'CAP-HIR', 'EQU-CAB'], isNotifiable: true, wahisCategory: 'multiple_species' },
  { code: 'BRU-B', nameEn: 'Brucellosis (Brucella abortus)', nameFr: 'Brucellose (Brucella abortus)', namePt: 'Brucelose (Brucella abortus)', nameAr: 'داء البروسيلات (بروسيلا أبورتس)', isWoahListed: true, affectedSpecies: ['BOS-TAU', 'BOS-IND', 'BUB-BUB'], isNotifiable: true, wahisCategory: 'cattle' },
  { code: 'BRU-M', nameEn: 'Brucellosis (Brucella melitensis)', nameFr: 'Brucellose (Brucella melitensis)', namePt: 'Brucelose (Brucella melitensis)', nameAr: 'داء البروسيلات (بروسيلا ميليتنسس)', isWoahListed: true, affectedSpecies: ['OVI-ARI', 'CAP-HIR'], isNotifiable: true, wahisCategory: 'small_ruminants' },
  { code: 'BTB', nameEn: 'Bovine tuberculosis', nameFr: 'Tuberculose bovine', namePt: 'Tuberculose bovina', nameAr: 'السل البقري', isWoahListed: true, affectedSpecies: ['BOS-TAU', 'BOS-IND', 'BUB-BUB', 'SYN-CAF'], isNotifiable: true, wahisCategory: 'cattle' },
  { code: 'CSF', nameEn: 'Classical swine fever', nameFr: 'Peste porcine classique', namePt: 'Peste suína clássica', nameAr: 'حمى الخنازير الكلاسيكية', isWoahListed: true, affectedSpecies: ['SUS-DOM'], isNotifiable: true, wahisCategory: 'swine' },
  { code: 'ECF', nameEn: 'Theileriosis (East Coast fever)', nameFr: 'Theilériose (fièvre de la côte Est)', namePt: 'Teileriose (febre da costa leste)', nameAr: 'الثيليريا (حمى الساحل الشرقي)', isWoahListed: true, affectedSpecies: ['BOS-TAU', 'BOS-IND', 'BUB-BUB'], isNotifiable: true, wahisCategory: 'cattle' },
  { code: 'TRY', nameEn: 'Trypanosomosis (tsetse-transmitted)', nameFr: 'Trypanosomose (transmise par la tsé-tsé)', namePt: 'Tripanossomose (transmitida pela tsé-tsé)', nameAr: 'داء المثقبيات (المنقول بذبابة تسي تسي)', isWoahListed: true, affectedSpecies: ['BOS-TAU', 'BOS-IND', 'EQU-CAB', 'CAM-DRO'], isNotifiable: true, wahisCategory: 'multiple_species' },
  { code: 'BRD', nameEn: 'Bovine viral diarrhoea', nameFr: 'Diarrhée virale bovine', namePt: 'Diarreia viral bovina', nameAr: 'الإسهال الفيروسي البقري', isWoahListed: true, affectedSpecies: ['BOS-TAU', 'BOS-IND'], isNotifiable: true, wahisCategory: 'cattle' },
  { code: 'IBR', nameEn: 'Infectious bovine rhinotracheitis', nameFr: 'Rhinotrachéite infectieuse bovine', namePt: 'Rinotraqueíte infecciosa bovina', nameAr: 'التهاب الأنف والقصبة الهوائية المعدي البقري', isWoahListed: true, affectedSpecies: ['BOS-TAU', 'BOS-IND'], isNotifiable: true, wahisCategory: 'cattle' },
  { code: 'HS', nameEn: 'Haemorrhagic septicaemia', nameFr: 'Septicémie hémorragique', namePt: 'Septicemia hemorrágica', nameAr: 'تسمم الدم النزفي', isWoahListed: true, affectedSpecies: ['BOS-TAU', 'BOS-IND', 'BUB-BUB'], isNotifiable: true, wahisCategory: 'cattle' },
  { code: 'AHS', nameEn: 'African horse sickness', nameFr: 'Peste équine', namePt: 'Peste equina africana', nameAr: 'الطاعون الخيلي الأفريقي', isWoahListed: true, affectedSpecies: ['EQU-CAB', 'EQU-ASI', 'EQU-MUL'], isNotifiable: true, wahisCategory: 'equine' },
  { code: 'GLN', nameEn: 'Glanders', nameFr: 'Morve', namePt: 'Mormo', nameAr: 'الرعام', isWoahListed: true, affectedSpecies: ['EQU-CAB', 'EQU-ASI'], isNotifiable: true, wahisCategory: 'equine' },
  { code: 'RHD', nameEn: 'Rabbit haemorrhagic disease', nameFr: 'Maladie hémorragique du lapin', namePt: 'Doença hemorrágica do coelho', nameAr: 'مرض النزف الدموي في الأرانب', isWoahListed: true, affectedSpecies: ['ORC-CUN'], isNotifiable: true, wahisCategory: 'lagomorph' },
  { code: 'MYX', nameEn: 'Myxomatosis', nameFr: 'Myxomatose', namePt: 'Mixomatose', nameAr: 'الورم المخاطي', isWoahListed: true, affectedSpecies: ['ORC-CUN'], isNotifiable: true, wahisCategory: 'lagomorph' },
  { code: 'VAR', nameEn: 'Varroosis of honey bees', nameFr: 'Varroose des abeilles mellifères', namePt: 'Varroose das abelhas melíferas', nameAr: 'داء الفاروا في نحل العسل', isWoahListed: true, affectedSpecies: ['API-MEL', 'API-ADA', 'API-SCU'], isNotifiable: true, wahisCategory: 'bee' },
  { code: 'AFB', nameEn: 'American foulbrood of honey bees', nameFr: 'Loque américaine des abeilles mellifères', namePt: 'Loque americana das abelhas', nameAr: 'تعفن الحضنة الأمريكي', isWoahListed: true, affectedSpecies: ['API-MEL', 'API-ADA', 'API-SCU'], isNotifiable: true, wahisCategory: 'bee' },
  { code: 'SHB', nameEn: 'Small hive beetle infestation', nameFr: 'Infestation par le petit coléoptère', namePt: 'Infestação pelo pequeno besouro da colmeia', nameAr: 'الإصابة بخنفساء الخلية الصغيرة', isWoahListed: true, affectedSpecies: ['API-MEL', 'API-ADA', 'API-SCU'], isNotifiable: true, wahisCategory: 'bee' },
  { code: 'EUS', nameEn: 'Epizootic ulcerative syndrome', nameFr: 'Syndrome ulcératif épizootique', namePt: 'Síndrome ulcerativa epizoótica', nameAr: 'متلازمة القرحة الوبائية', isWoahListed: true, affectedSpecies: ['ORE-NIL', 'CLA-GAR', 'LAT-NIL'], isNotifiable: true, wahisCategory: 'fish' },
  { code: 'WSSV', nameEn: 'White spot disease', nameFr: 'Maladie des points blancs', namePt: 'Doença das manchas brancas', nameAr: 'مرض البقع البيضاء', isWoahListed: true, affectedSpecies: ['PEN-MON'], isNotifiable: true, wahisCategory: 'crustacean' },

  // ── Additional WOAH-listed cattle diseases ──
  { code: 'ANA-BOV', nameEn: 'Bovine anaplasmosis', nameFr: 'Anaplasmose bovine', namePt: 'Anaplasmose bovina', nameAr: 'داء الأنابلازما البقري', isWoahListed: true, affectedSpecies: ['BOS-TAU', 'BOS-IND'], isNotifiable: true, wahisCategory: 'cattle' },
  { code: 'BAB-BOV', nameEn: 'Bovine babesiosis', nameFr: 'Babésiose bovine', namePt: 'Babesiose bovina', nameAr: 'داء البابيزيا البقري', isWoahListed: true, affectedSpecies: ['BOS-TAU', 'BOS-IND', 'BUB-BUB'], isNotifiable: true, wahisCategory: 'cattle' },
  { code: 'BSE', nameEn: 'Bovine spongiform encephalopathy', nameFr: 'Encéphalopathie spongiforme bovine', namePt: 'Encefalopatia espongiforme bovina', nameAr: 'اعتلال الدماغ الإسفنجي البقري', isWoahListed: true, affectedSpecies: ['BOS-TAU', 'BOS-IND'], isNotifiable: true, wahisCategory: 'cattle' },
  { code: 'BEN', nameEn: 'Bovine genital campylobacteriosis', nameFr: 'Campylobactériose génitale bovine', namePt: 'Campilobacteriose genital bovina', nameAr: 'داء العطيفات التناسلي البقري', isWoahListed: true, affectedSpecies: ['BOS-TAU', 'BOS-IND'], isNotifiable: true, wahisCategory: 'cattle' },
  { code: 'TRI-FOE', nameEn: 'Trichomonosis', nameFr: 'Trichomonose', namePt: 'Tricomonose', nameAr: 'داء المشعرات', isWoahListed: true, affectedSpecies: ['BOS-TAU', 'BOS-IND'], isNotifiable: true, wahisCategory: 'cattle' },
  { code: 'ENZ-BOV', nameEn: 'Enzootic bovine leukosis', nameFr: 'Leucose bovine enzootique', namePt: 'Leucose bovina enzoótica', nameAr: 'ابيضاض الدم البقري المتوطن', isWoahListed: true, affectedSpecies: ['BOS-TAU', 'BOS-IND'], isNotifiable: true, wahisCategory: 'cattle' },
  { code: 'RPD', nameEn: 'Rinderpest', nameFr: 'Peste bovine', namePt: 'Peste bovina', nameAr: 'الطاعون البقري', isWoahListed: true, affectedSpecies: ['BOS-TAU', 'BOS-IND', 'BUB-BUB', 'SYN-CAF'], isNotifiable: true, wahisCategory: 'cattle' },
  { code: 'DER-DIG', nameEn: 'Bovine dermatophilosis', nameFr: 'Dermatophilose bovine', namePt: 'Dermatofilose bovina', nameAr: 'الفطار الجلدي البقري', isWoahListed: false, affectedSpecies: ['BOS-TAU', 'BOS-IND'], isNotifiable: false, wahisCategory: 'cattle' },
  { code: 'COW-POX', nameEn: 'Cowdriosis (heartwater)', nameFr: 'Cowdriose (heartwater)', namePt: 'Cowdriose (heartwater)', nameAr: 'الكاودريوز (هارتووتر)', isWoahListed: true, affectedSpecies: ['BOS-TAU', 'BOS-IND', 'OVI-ARI', 'CAP-HIR'], isNotifiable: true, wahisCategory: 'multiple_species' },

  // ── Additional small ruminant diseases ──
  { code: 'CCPP', nameEn: 'Contagious caprine pleuropneumonia', nameFr: 'Pleuropneumonie contagieuse caprine', namePt: 'Pleuropneumonia contagiosa caprina', nameAr: 'الالتهاب الرئوي البلوري المعدي في الماعز', isWoahListed: true, affectedSpecies: ['CAP-HIR'], isNotifiable: true, wahisCategory: 'small_ruminants' },
  { code: 'OCA', nameEn: 'Ovine chlamydiosis (enzootic abortion)', nameFr: 'Chlamydiose ovine', namePt: 'Clamidiose ovina', nameAr: 'داء الكلاميديا في الأغنام', isWoahListed: true, affectedSpecies: ['OVI-ARI', 'CAP-HIR'], isNotifiable: true, wahisCategory: 'small_ruminants' },
  { code: 'SCR', nameEn: 'Scrapie', nameFr: 'Tremblante du mouton', namePt: 'Scrapie', nameAr: 'الاعتلال الدماغي الإسفنجي في الأغنام', isWoahListed: true, affectedSpecies: ['OVI-ARI', 'CAP-HIR'], isNotifiable: true, wahisCategory: 'small_ruminants' },
  { code: 'MAE-VIS', nameEn: 'Maedi-visna', nameFr: 'Maedi-visna', namePt: 'Maedi-visna', nameAr: 'مايدي فيسنا', isWoahListed: true, affectedSpecies: ['OVI-ARI'], isNotifiable: true, wahisCategory: 'small_ruminants' },
  { code: 'NAI-SHE', nameEn: 'Nairobi sheep disease', nameFr: 'Maladie de Nairobi', namePt: 'Doença de Nairobi', nameAr: 'مرض نيروبي في الأغنام', isWoahListed: true, affectedSpecies: ['OVI-ARI', 'CAP-HIR'], isNotifiable: true, wahisCategory: 'small_ruminants' },
  { code: 'BLU', nameEn: 'Bluetongue', nameFr: 'Fièvre catarrhale du mouton', namePt: 'Língua azul', nameAr: 'اللسان الأزرق', isWoahListed: true, affectedSpecies: ['OVI-ARI', 'CAP-HIR', 'BOS-TAU'], isNotifiable: true, wahisCategory: 'small_ruminants' },
  { code: 'EPI-HEM', nameEn: 'Epizootic haemorrhagic disease', nameFr: 'Maladie hémorragique épizootique', namePt: 'Doença hemorrágica epizoótica', nameAr: 'المرض النزفي الوبائي', isWoahListed: true, affectedSpecies: ['BOS-TAU', 'OVI-ARI', 'CAP-HIR'], isNotifiable: true, wahisCategory: 'multiple_species' },

  // ── Additional swine diseases ──
  { code: 'PED', nameEn: 'Porcine epidemic diarrhoea', nameFr: 'Diarrhée épidémique porcine', namePt: 'Diarreia epidémica suína', nameAr: 'الإسهال الوبائي في الخنازير', isWoahListed: false, affectedSpecies: ['SUS-DOM'], isNotifiable: false, wahisCategory: 'swine' },
  { code: 'PRRS', nameEn: 'Porcine reproductive and respiratory syndrome', nameFr: 'Syndrome reproducteur et respiratoire porcin', namePt: 'Síndrome reprodutiva e respiratória suína', nameAr: 'متلازمة الخنازير التنفسية والتناسلية', isWoahListed: true, affectedSpecies: ['SUS-DOM'], isNotifiable: true, wahisCategory: 'swine' },
  { code: 'AUJ', nameEn: "Aujeszky's disease", nameFr: "Maladie d'Aujeszky", namePt: 'Doença de Aujeszky', nameAr: 'مرض أوجيسزكي', isWoahListed: true, affectedSpecies: ['SUS-DOM'], isNotifiable: true, wahisCategory: 'swine' },
  { code: 'TGE', nameEn: 'Transmissible gastroenteritis', nameFr: 'Gastro-entérite transmissible', namePt: 'Gastroenterite transmissível', nameAr: 'التهاب المعدة والأمعاء المعدي', isWoahListed: true, affectedSpecies: ['SUS-DOM'], isNotifiable: true, wahisCategory: 'swine' },
  { code: 'SWI-EYR', nameEn: 'Swine erysipelas', nameFr: 'Rouget du porc', namePt: 'Erisipela suína', nameAr: 'الحمرة في الخنازير', isWoahListed: false, affectedSpecies: ['SUS-DOM'], isNotifiable: false, wahisCategory: 'swine' },
  { code: 'SWI-INF', nameEn: 'Swine influenza', nameFr: 'Grippe porcine', namePt: 'Gripe suína', nameAr: 'إنفلونزا الخنازير', isWoahListed: true, affectedSpecies: ['SUS-DOM'], isNotifiable: true, wahisCategory: 'swine' },
  { code: 'CYS-SUI', nameEn: 'Porcine cysticercosis', nameFr: 'Cysticercose porcine', namePt: 'Cisticercose suína', nameAr: 'داء الكيسات المذنبة في الخنازير', isWoahListed: true, affectedSpecies: ['SUS-DOM'], isNotifiable: true, wahisCategory: 'swine' },

  // ── Additional avian diseases ──
  { code: 'IBD', nameEn: 'Infectious bursal disease (Gumboro)', nameFr: 'Maladie de Gumboro', namePt: 'Doença de Gumboro', nameAr: 'مرض غامبورو', isWoahListed: true, affectedSpecies: ['GAL-DOM'], isNotifiable: true, wahisCategory: 'avian' },
  { code: 'AVI-MYC', nameEn: 'Avian mycoplasmosis', nameFr: 'Mycoplasmose aviaire', namePt: 'Micoplasmose aviária', nameAr: 'داء الميكوبلازما الطيري', isWoahListed: true, affectedSpecies: ['GAL-DOM', 'MEL-GAL'], isNotifiable: true, wahisCategory: 'avian' },
  { code: 'ILT', nameEn: 'Infectious laryngotracheitis', nameFr: 'Laryngotrachéite infectieuse', namePt: 'Laringotraqueíte infecciosa', nameAr: 'التهاب الحنجرة والقصبة الهوائية المعدي', isWoahListed: true, affectedSpecies: ['GAL-DOM'], isNotifiable: true, wahisCategory: 'avian' },
  { code: 'AVI-POX', nameEn: 'Fowl pox', nameFr: 'Variole aviaire', namePt: 'Varíola aviária', nameAr: 'جدري الطيور', isWoahListed: true, affectedSpecies: ['GAL-DOM', 'MEL-GAL', 'COL-LIV'], isNotifiable: true, wahisCategory: 'avian' },
  { code: 'AVI-CHO', nameEn: 'Fowl cholera', nameFr: 'Choléra aviaire', namePt: 'Cólera aviária', nameAr: 'كوليرا الطيور', isWoahListed: true, affectedSpecies: ['GAL-DOM', 'ANA-PLA', 'ANS-DOM', 'MEL-GAL'], isNotifiable: true, wahisCategory: 'avian' },
  { code: 'MAR-DIS', nameEn: 'Marek\'s disease', nameFr: 'Maladie de Marek', namePt: 'Doença de Marek', nameAr: 'مرض ماريك', isWoahListed: true, affectedSpecies: ['GAL-DOM'], isNotifiable: true, wahisCategory: 'avian' },
  { code: 'AVI-SAL', nameEn: 'Salmonellosis (pullorum/typhoid)', nameFr: 'Salmonellose aviaire', namePt: 'Salmonelose aviária', nameAr: 'داء السالمونيلا الطيري', isWoahListed: true, affectedSpecies: ['GAL-DOM', 'MEL-GAL'], isNotifiable: true, wahisCategory: 'avian' },
  { code: 'AVI-TUB', nameEn: 'Avian tuberculosis', nameFr: 'Tuberculose aviaire', namePt: 'Tuberculose aviária', nameAr: 'السل الطيري', isWoahListed: true, affectedSpecies: ['GAL-DOM'], isNotifiable: true, wahisCategory: 'avian' },
  { code: 'DUC-VIR', nameEn: 'Duck virus hepatitis', nameFr: 'Hépatite virale du canard', namePt: 'Hepatite viral do pato', nameAr: 'التهاب الكبد الفيروسي في البط', isWoahListed: true, affectedSpecies: ['ANA-PLA'], isNotifiable: true, wahisCategory: 'avian' },
  { code: 'DUC-PLG', nameEn: 'Duck plague (duck virus enteritis)', nameFr: 'Peste du canard', namePt: 'Peste do pato', nameAr: 'طاعون البط', isWoahListed: true, affectedSpecies: ['ANA-PLA', 'ANS-DOM'], isNotifiable: true, wahisCategory: 'avian' },

  // ── Equine diseases ──
  { code: 'EIA', nameEn: 'Equine infectious anaemia', nameFr: 'Anémie infectieuse des équidés', namePt: 'Anemia infecciosa equina', nameAr: 'فقر الدم المعدي في الخيول', isWoahListed: true, affectedSpecies: ['EQU-CAB', 'EQU-ASI', 'EQU-MUL'], isNotifiable: true, wahisCategory: 'equine' },
  { code: 'EHV', nameEn: 'Equine herpesvirus (EHV-1 / EHV-4)', nameFr: 'Herpèsvirose équine', namePt: 'Herpesvírus equino (EHV-1 / EHV-4)', nameAr: 'فيروس الهربس الخيلي', isWoahListed: true, affectedSpecies: ['EQU-CAB', 'EQU-ASI'], isNotifiable: true, wahisCategory: 'equine' },
  { code: 'EAV', nameEn: 'Equine viral arteritis', nameFr: 'Artérite virale équine', namePt: 'Arterite viral equina', nameAr: 'التهاب الشرايين الفيروسي الخيلي', isWoahListed: true, affectedSpecies: ['EQU-CAB'], isNotifiable: true, wahisCategory: 'equine' },
  { code: 'EQU-PIR', nameEn: 'Equine piroplasmosis', nameFr: 'Piroplasmose équine', namePt: 'Piroplasmose equina', nameAr: 'داء البيروبلازما الخيلي', isWoahListed: true, affectedSpecies: ['EQU-CAB', 'EQU-ASI', 'EQU-MUL'], isNotifiable: true, wahisCategory: 'equine' },
  { code: 'SUR-EQU', nameEn: 'Surra (Trypanosoma evansi)', nameFr: 'Surra', namePt: 'Surra (Trypanosoma evansi)', nameAr: 'السرا (تريبانوسوما إيفانسي)', isWoahListed: true, affectedSpecies: ['EQU-CAB', 'CAM-DRO', 'BOS-TAU'], isNotifiable: true, wahisCategory: 'multiple_species' },
  { code: 'DOU-EQU', nameEn: 'Dourine', nameFr: 'Dourine', namePt: 'Durina', nameAr: 'الدورين', isWoahListed: true, affectedSpecies: ['EQU-CAB', 'EQU-ASI'], isNotifiable: true, wahisCategory: 'equine' },
  { code: 'VEE', nameEn: 'Venezuelan equine encephalomyelitis', nameFr: 'Encéphalomyélite équine vénézuélienne', namePt: 'Encefalomielite equina venezuelana', nameAr: 'التهاب الدماغ الخيلي الفنزويلي', isWoahListed: true, affectedSpecies: ['EQU-CAB'], isNotifiable: true, wahisCategory: 'equine' },
  { code: 'WNF', nameEn: 'West Nile fever', nameFr: 'Fièvre du Nil occidental', namePt: 'Febre do Nilo Ocidental', nameAr: 'حمى غرب النيل', isWoahListed: true, affectedSpecies: ['EQU-CAB', 'GAL-DOM'], isNotifiable: true, wahisCategory: 'multiple_species' },

  // ── Camelid diseases ──
  { code: 'CAM-POX', nameEn: 'Camelpox', nameFr: 'Variole du chameau', namePt: 'Varíola do camelo', nameAr: 'جدري الإبل', isWoahListed: true, affectedSpecies: ['CAM-DRO', 'CAM-BAC'], isNotifiable: true, wahisCategory: 'camelid' },
  { code: 'MERS', nameEn: 'Middle East respiratory syndrome', nameFr: 'Syndrome respiratoire du Moyen-Orient', namePt: 'Síndrome respiratória do Médio Oriente', nameAr: 'متلازمة الشرق الأوسط التنفسية', isWoahListed: false, affectedSpecies: ['CAM-DRO'], isNotifiable: false, wahisCategory: 'camelid' },

  // ── Multi-species / zoonotic diseases ──
  { code: 'DERA', nameEn: 'Dermatophytosis (ringworm)', nameFr: 'Dermatophytose (teigne)', namePt: 'Dermatofitose (tinha)', nameAr: 'الفطار الجلدي (السعفة)', isWoahListed: false, affectedSpecies: ['BOS-TAU', 'OVI-ARI', 'CAP-HIR', 'EQU-CAB', 'CAN-FAM', 'FEL-CAT'], isNotifiable: false, wahisCategory: 'multiple_species' },
  { code: 'LEP', nameEn: 'Leptospirosis', nameFr: 'Leptospirose', namePt: 'Leptospirose', nameAr: 'داء البريميات', isWoahListed: true, affectedSpecies: ['BOS-TAU', 'SUS-DOM', 'CAN-FAM', 'OVI-ARI'], isNotifiable: true, wahisCategory: 'multiple_species' },
  { code: 'QFV', nameEn: 'Q fever (Coxiella burnetii)', nameFr: 'Fièvre Q', namePt: 'Febre Q (Coxiella burnetii)', nameAr: 'حمى كيو', isWoahListed: true, affectedSpecies: ['BOS-TAU', 'OVI-ARI', 'CAP-HIR'], isNotifiable: true, wahisCategory: 'multiple_species' },
  { code: 'TUL', nameEn: 'Tularemia', nameFr: 'Tularémie', namePt: 'Tularemia', nameAr: 'التولاريميا', isWoahListed: true, affectedSpecies: ['ORC-CUN', 'OVI-ARI'], isNotifiable: true, wahisCategory: 'multiple_species' },
  { code: 'LEISH', nameEn: 'Leishmaniosis', nameFr: 'Leishmaniose', namePt: 'Leishmaniose', nameAr: 'داء الليشمانيات', isWoahListed: true, affectedSpecies: ['CAN-FAM'], isNotifiable: true, wahisCategory: 'multiple_species' },
  { code: 'ECH-GRA', nameEn: 'Echinococcosis/hydatidosis', nameFr: 'Échinococcose/hydatidose', namePt: 'Equinococose/hidatidose', nameAr: 'داء المشوكات/الأكياس العدارية', isWoahListed: true, affectedSpecies: ['CAN-FAM', 'OVI-ARI', 'BOS-TAU', 'CAP-HIR'], isNotifiable: true, wahisCategory: 'multiple_species' },
  { code: 'PAR-ASF', nameEn: 'Paratuberculosis (Johne\'s disease)', nameFr: 'Paratuberculose (maladie de Johne)', namePt: 'Paratuberculose (doença de Johne)', nameAr: 'نظير السل (مرض جون)', isWoahListed: true, affectedSpecies: ['BOS-TAU', 'OVI-ARI', 'CAP-HIR'], isNotifiable: true, wahisCategory: 'multiple_species' },
  { code: 'TOX', nameEn: 'Toxoplasmosis', nameFr: 'Toxoplasmose', namePt: 'Toxoplasmose', nameAr: 'داء المقوسات', isWoahListed: false, affectedSpecies: ['FEL-CAT', 'OVI-ARI', 'CAP-HIR'], isNotifiable: false, wahisCategory: 'multiple_species' },
  { code: 'CRI-CON', nameEn: 'Crimean-Congo haemorrhagic fever', nameFr: 'Fièvre hémorragique de Crimée-Congo', namePt: 'Febre hemorrágica da Crimeia-Congo', nameAr: 'حمى القرم-الكونغو النزفية', isWoahListed: true, affectedSpecies: ['BOS-TAU', 'OVI-ARI', 'CAP-HIR'], isNotifiable: true, wahisCategory: 'multiple_species' },
  { code: 'EBO-VIR', nameEn: 'Ebola virus disease (animal)', nameFr: 'Maladie à virus Ebola (animal)', namePt: 'Doença por vírus Ébola (animal)', nameAr: 'مرض فيروس إيبولا (حيواني)', isWoahListed: false, affectedSpecies: ['GOR-GOR', 'PAN-TRO'], isNotifiable: true, wahisCategory: 'wildlife' },
  { code: 'MPX', nameEn: 'Mpox (monkeypox)', nameFr: 'Variole du singe', namePt: 'Mpox (varíola dos macacos)', nameAr: 'جدري القردة', isWoahListed: false, affectedSpecies: ['PAP-ANU', 'CER-AET', 'CRI-GAM'], isNotifiable: true, wahisCategory: 'wildlife' },

  // ── Aquatic diseases ──
  { code: 'KHV', nameEn: 'Koi herpesvirus disease', nameFr: 'Herpèsvirose de la carpe koï', namePt: 'Herpesvírus da carpa koi', nameAr: 'فيروس هربس سمك الكوي', isWoahListed: true, affectedSpecies: ['CYP-CAR'], isNotifiable: true, wahisCategory: 'fish' },
  { code: 'SVC', nameEn: 'Spring viraemia of carp', nameFr: 'Virémie printanière de la carpe', namePt: 'Viremia primaveril da carpa', nameAr: 'فيروس الربيع في الشبوط', isWoahListed: true, affectedSpecies: ['CYP-CAR'], isNotifiable: true, wahisCategory: 'fish' },
  { code: 'IHN', nameEn: 'Infectious haematopoietic necrosis', nameFr: 'Nécrose hématopoïétique infectieuse', namePt: 'Necrose hematopoiética infecciosa', nameAr: 'النخر المكون للدم المعدي', isWoahListed: true, affectedSpecies: ['ORE-NIL', 'ONC-MYK'], isNotifiable: true, wahisCategory: 'fish' },
  { code: 'VHS', nameEn: 'Viral haemorrhagic septicaemia', nameFr: 'Septicémie hémorragique virale', namePt: 'Septicemia hemorrágica viral', nameAr: 'تسمم الدم النزفي الفيروسي', isWoahListed: true, affectedSpecies: ['ORE-NIL', 'CLA-GAR', 'ONC-MYK'], isNotifiable: true, wahisCategory: 'fish' },
  { code: 'TIL-VIR', nameEn: 'Tilapia lake virus disease', nameFr: 'Maladie du virus du lac du tilapia', namePt: 'Doença do vírus do lago da tilápia', nameAr: 'مرض فيروس بحيرة البلطي', isWoahListed: true, affectedSpecies: ['ORE-NIL', 'ORE-AUR'], isNotifiable: true, wahisCategory: 'fish' },
  { code: 'ISA', nameEn: 'Infectious salmon anaemia', nameFr: 'Anémie infectieuse du saumon', namePt: 'Anemia infecciosa do salmão', nameAr: 'فقر الدم المعدي في السلمون', isWoahListed: true, affectedSpecies: ['ONC-MYK'], isNotifiable: true, wahisCategory: 'fish' },

  // ── Bee diseases ──
  { code: 'EFB', nameEn: 'European foulbrood of honey bees', nameFr: 'Loque européenne des abeilles mellifères', namePt: 'Loque europeia das abelhas', nameAr: 'تعفن الحضنة الأوروبي', isWoahListed: true, affectedSpecies: ['API-MEL', 'API-ADA', 'API-SCU'], isNotifiable: true, wahisCategory: 'bee' },
  { code: 'NOS-BEE', nameEn: 'Nosemosis of honey bees', nameFr: 'Nosémose des abeilles mellifères', namePt: 'Nosemose das abelhas melíferas', nameAr: 'داء النوزيما في نحل العسل', isWoahListed: true, affectedSpecies: ['API-MEL', 'API-ADA', 'API-SCU'], isNotifiable: true, wahisCategory: 'bee' },
  { code: 'TRO-BEE', nameEn: 'Tropilaelaps infestation', nameFr: 'Infestation par Tropilaelaps', namePt: 'Infestação por Tropilaelaps', nameAr: 'الإصابة بالتروبيلابس', isWoahListed: true, affectedSpecies: ['API-MEL'], isNotifiable: true, wahisCategory: 'bee' },

  // ── Dog/cat diseases ──
  { code: 'CDV', nameEn: 'Canine distemper', nameFr: 'Maladie de Carré', namePt: 'Cinomose canina', nameAr: 'حمى الكلاب', isWoahListed: false, affectedSpecies: ['CAN-FAM', 'LYC-PIC'], isNotifiable: false, wahisCategory: 'multiple_species' },
  { code: 'CPV', nameEn: 'Canine parvovirus', nameFr: 'Parvovirose canine', namePt: 'Parvovirose canina', nameAr: 'فيروس بارفو الكلاب', isWoahListed: false, affectedSpecies: ['CAN-FAM'], isNotifiable: false, wahisCategory: 'multiple_species' },
  { code: 'FPV', nameEn: 'Feline panleukopenia', nameFr: 'Panleucopénie féline', namePt: 'Panleucopenia felina', nameAr: 'نقص الكريات البيض الشامل في القطط', isWoahListed: false, affectedSpecies: ['FEL-CAT'], isNotifiable: false, wahisCategory: 'multiple_species' },
  { code: 'FIV', nameEn: 'Feline immunodeficiency virus', nameFr: "Virus de l'immunodéficience féline", namePt: 'Vírus da imunodeficiência felina', nameAr: 'فيروس نقص المناعة في القطط', isWoahListed: false, affectedSpecies: ['FEL-CAT'], isNotifiable: false, wahisCategory: 'multiple_species' },

  // ── Wildlife diseases ──
  { code: 'RHDV2', nameEn: 'Rabbit haemorrhagic disease virus 2', nameFr: 'Maladie hémorragique du lapin virus 2', namePt: 'Doença hemorrágica do coelho vírus 2', nameAr: 'مرض النزف الدموي في الأرانب فيروس 2', isWoahListed: true, affectedSpecies: ['ORC-CUN'], isNotifiable: true, wahisCategory: 'lagomorph' },
  { code: 'SAR-MNG', nameEn: 'Sarcoptic mange', nameFr: 'Gale sarcoptique', namePt: 'Sarna sarcóptica', nameAr: 'الجرب القارمي', isWoahListed: false, affectedSpecies: ['CAN-FAM', 'SUS-DOM', 'CAM-DRO', 'OVI-ARI'], isNotifiable: false, wahisCategory: 'multiple_species' },
  { code: 'ASP-FUM', nameEn: 'Aspergillosis (avian)', nameFr: 'Aspergillose aviaire', namePt: 'Aspergilose aviária', nameAr: 'داء الرشاشيات الطيري', isWoahListed: false, affectedSpecies: ['GAL-DOM', 'MEL-GAL', 'PSI-ERY'], isNotifiable: false, wahisCategory: 'avian' },

  // ── Regional/emerging African diseases ──
  { code: 'AHFV', nameEn: 'Alkhurma haemorrhagic fever', nameFr: "Fièvre hémorragique d'Alkhurma", namePt: 'Febre hemorrágica de Alkhurma', nameAr: 'حمى الخرمة النزفية', isWoahListed: false, affectedSpecies: ['OVI-ARI', 'CAM-DRO'], isNotifiable: true, wahisCategory: 'multiple_species' },
  { code: 'WES-EQU', nameEn: 'Western equine encephalitis', nameFr: "Encéphalite équine de l'Ouest", namePt: 'Encefalite equina do Oeste', nameAr: 'التهاب الدماغ الخيلي الغربي', isWoahListed: true, affectedSpecies: ['EQU-CAB'], isNotifiable: true, wahisCategory: 'equine' },
  { code: 'EAS-EQU', nameEn: 'Eastern equine encephalitis', nameFr: "Encéphalite équine de l'Est", namePt: 'Encefalite equina do Leste', nameAr: 'التهاب الدماغ الخيلي الشرقي', isWoahListed: true, affectedSpecies: ['EQU-CAB'], isNotifiable: true, wahisCategory: 'equine' },
  { code: 'BRU-SUI', nameEn: 'Brucellosis (Brucella suis)', nameFr: 'Brucellose (Brucella suis)', namePt: 'Brucelose (Brucella suis)', nameAr: 'داء البروسيلات (بروسيلا سويس)', isWoahListed: true, affectedSpecies: ['SUS-DOM'], isNotifiable: true, wahisCategory: 'swine' },
  { code: 'BRU-OVI', nameEn: 'Brucellosis (Brucella ovis)', nameFr: 'Brucellose (Brucella ovis)', namePt: 'Brucelose (Brucella ovis)', nameAr: 'داء البروسيلات (بروسيلا أوفيس)', isWoahListed: true, affectedSpecies: ['OVI-ARI'], isNotifiable: true, wahisCategory: 'small_ruminants' },
  { code: 'BRU-CAN', nameEn: 'Brucellosis (Brucella canis)', nameFr: 'Brucellose (Brucella canis)', namePt: 'Brucelose (Brucella canis)', nameAr: 'داء البروسيلات (بروسيلا كانيس)', isWoahListed: true, affectedSpecies: ['CAN-FAM'], isNotifiable: true, wahisCategory: 'multiple_species' },
  { code: 'TAE-SAG', nameEn: 'Cysticercosis (Taenia saginata)', nameFr: 'Cysticercose (Taenia saginata)', namePt: 'Cisticercose (Taenia saginata)', nameAr: 'داء الكيسات المذنبة (الشريطية العزلاء)', isWoahListed: true, affectedSpecies: ['BOS-TAU'], isNotifiable: true, wahisCategory: 'cattle' },
  { code: 'FAS-HEP', nameEn: 'Fasciolosis (liver fluke)', nameFr: 'Fasciolose (douve du foie)', namePt: 'Fasciolose (dístoma hepático)', nameAr: 'داء المتورقات (الديدان الكبدية)', isWoahListed: false, affectedSpecies: ['BOS-TAU', 'OVI-ARI', 'CAP-HIR'], isNotifiable: false, wahisCategory: 'multiple_species' },
  { code: 'HAE-PAR', nameEn: 'Haemonchosis', nameFr: 'Haemonchose', namePt: 'Hemoncose', nameAr: 'داء الدودة السلكية', isWoahListed: false, affectedSpecies: ['OVI-ARI', 'CAP-HIR', 'BOS-TAU'], isNotifiable: false, wahisCategory: 'multiple_species' },
  { code: 'THE-PAR', nameEn: 'Tropical theileriosis', nameFr: 'Theilériose tropicale', namePt: 'Teileriose tropical', nameAr: 'الثيليريا المدارية', isWoahListed: true, affectedSpecies: ['BOS-TAU', 'BOS-IND'], isNotifiable: true, wahisCategory: 'cattle' },
  { code: 'PNE-EFB', nameEn: 'Contagious equine metritis', nameFr: 'Métrite contagieuse équine', namePt: 'Metrite contagiosa equina', nameAr: 'التهاب الرحم المعدي في الخيول', isWoahListed: true, affectedSpecies: ['EQU-CAB'], isNotifiable: true, wahisCategory: 'equine' },
  { code: 'ACT', nameEn: 'Actinomycosis', nameFr: 'Actinomycose', namePt: 'Actinomicose', nameAr: 'داء الشعيات', isWoahListed: false, affectedSpecies: ['BOS-TAU'], isNotifiable: false, wahisCategory: 'cattle' },
  { code: 'BKC', nameEn: 'Bovine keratoconjunctivitis', nameFr: 'Kératoconjonctivite bovine', namePt: 'Queratoconjuntivite bovina', nameAr: 'التهاب القرنية والملتحمة البقري', isWoahListed: false, affectedSpecies: ['BOS-TAU', 'BOS-IND'], isNotifiable: false, wahisCategory: 'cattle' },
  { code: 'CLO-PER', nameEn: 'Enterotoxemia (Clostridium perfringens)', nameFr: 'Entérotoxémie', namePt: 'Enterotoxemia (Clostridium perfringens)', nameAr: 'التسمم المعوي (كلوستريديوم بيرفرنجنز)', isWoahListed: false, affectedSpecies: ['OVI-ARI', 'CAP-HIR', 'BOS-TAU'], isNotifiable: false, wahisCategory: 'multiple_species' },
  { code: 'BLK-LEG', nameEn: 'Blackleg (Clostridium chauvoei)', nameFr: 'Charbon symptomatique', namePt: 'Carbúnculo sintomático', nameAr: 'الحمى الفحمية العرضية', isWoahListed: false, affectedSpecies: ['BOS-TAU', 'OVI-ARI'], isNotifiable: false, wahisCategory: 'multiple_species' },
  { code: 'BOT', nameEn: 'Botulism', nameFr: 'Botulisme', namePt: 'Botulismo', nameAr: 'التسمم الوشيقي', isWoahListed: false, affectedSpecies: ['BOS-TAU', 'EQU-CAB', 'GAL-DOM'], isNotifiable: false, wahisCategory: 'multiple_species' },
  { code: 'TET', nameEn: 'Tetanus', nameFr: 'Tétanos', namePt: 'Tétano', nameAr: 'الكزاز', isWoahListed: false, affectedSpecies: ['EQU-CAB', 'OVI-ARI', 'BOS-TAU'], isNotifiable: false, wahisCategory: 'multiple_species' },
  { code: 'LIST', nameEn: 'Listeriosis', nameFr: 'Listériose', namePt: 'Listeriose', nameAr: 'داء الليستريات', isWoahListed: true, affectedSpecies: ['OVI-ARI', 'CAP-HIR', 'BOS-TAU'], isNotifiable: true, wahisCategory: 'multiple_species' },
  { code: 'PST-MUL', nameEn: 'Pasteurellosis', nameFr: 'Pasteurellose', namePt: 'Pasteurelose', nameAr: 'داء الباستوريلا', isWoahListed: false, affectedSpecies: ['BOS-TAU', 'OVI-ARI', 'BUB-BUB'], isNotifiable: false, wahisCategory: 'multiple_species' },
  { code: 'STR-EQI', nameEn: 'Strangles', nameFr: 'Gourme', namePt: 'Garrotilho', nameAr: 'الخناق الخيلي', isWoahListed: false, affectedSpecies: ['EQU-CAB', 'EQU-ASI'], isNotifiable: false, wahisCategory: 'equine' },
];
