'use client';

import React from 'react';

interface OfficialFooterProps {
  disclaimer?: string;
}

export function OfficialFooter({ disclaimer }: OfficialFooterProps) {
  return (
    <div className="print-footer mt-8 border-t-2 border-gray-900 pt-4">
      <div className="flex items-center justify-between text-xs text-gray-500">
        <div>
          <p className="font-semibold">AU-IBAR — ARIS 3.0</p>
          <p>Animal Resources Information System</p>
        </div>
        <div className="text-right">
          <p>P.O. Box 30786-00100, Nairobi, Kenya</p>
          <p>www.au-ibar.org</p>
        </div>
      </div>
      {disclaimer ? (
        <p className="mt-3 text-[10px] italic text-gray-400">{disclaimer}</p>
      ) : (
        <p className="mt-3 text-[10px] italic text-gray-400">
          This document is generated by ARIS 3.0. Data provenance and validation
          status should be verified before official use. Analytical data includes
          provenance disclaimers per AU-IBAR policy.
        </p>
      )}
    </div>
  );
}
