export enum QualityGate {
  COMPLETENESS = 'COMPLETENESS',
  TEMPORAL_CONSISTENCY = 'TEMPORAL_CONSISTENCY',
  GEOGRAPHIC_CONSISTENCY = 'GEOGRAPHIC_CONSISTENCY',
  CODES_VOCABULARIES = 'CODES_VOCABULARIES',
  UNITS = 'UNITS',
  DEDUPLICATION = 'DEDUPLICATION',
  AUDITABILITY = 'AUDITABILITY',
  CONFIDENCE_SCORE = 'CONFIDENCE_SCORE',
}

export enum QualityGateResult {
  PASS = 'PASS',
  FAIL = 'FAIL',
  WARNING = 'WARNING',
  SKIPPED = 'SKIPPED',
}
