export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  CONTINENTAL_ADMIN = 'CONTINENTAL_ADMIN',
  REC_ADMIN = 'REC_ADMIN',
  NATIONAL_ADMIN = 'NATIONAL_ADMIN',
  DATA_STEWARD = 'DATA_STEWARD',
  WAHIS_FOCAL_POINT = 'WAHIS_FOCAL_POINT',
  ANALYST = 'ANALYST',
  FIELD_AGENT = 'FIELD_AGENT',
}
