export enum WorkflowStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  PENDING_REVIEW = 'PENDING_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  ESCALATED = 'ESCALATED',
  WAHIS_READY = 'WAHIS_READY',
  ANALYTICS_READY = 'ANALYTICS_READY',
  PUBLISHED = 'PUBLISHED',
}
