package org.auibar.aris.mobile.ui.form.model

enum class FormFieldType {
    TEXT,
    TEXTAREA,
    NUMBER,
    DATE,
    TIME,
    SELECT,
    MULTI_SELECT,
    RADIO,
    TOGGLE,
    LOCATION,
    GEO_SELECTOR,
    SPECIES_SELECTOR,
    DISEASE_SELECTOR,
    ADMIN_CASCADER,
    PHOTO_CAPTURE,
    FILE_UPLOAD,
    HEADING,
    INFO_BOX,
    DIVIDER,
    REPEATER,
    CALCULATED,
    SIGNATURE,
}
