import type { LucideIcon } from 'lucide-react';
import {
  HeartPulse,
  Wheat,
  Fish,
  TrendingUp,
  PawPrint,
  Bug,
  Landmark,
  CloudSun,
  BookOpen,
  Layers,
  ShieldCheck,
  Syringe,
  Globe2,
  Leaf,
  ClipboardCheck,
  BarChart3,
  Building2,
  TreePine,
  Cloud,
  Activity,
  Microscope,
  Stethoscope,
  FlaskConical,
  MapPin,
  Shield,
  Scale,
  Truck,
  Anchor,
  Bird,
  Sprout,
  Sun,
  Thermometer,
  Droplets,
  GraduationCap,
  FileText,
  Database,
  Settings,
  Globe,
  Heart,
  Zap,
  Target,
  Award,
  BriefcaseMedical,
} from 'lucide-react';

/**
 * Maps icon name strings (stored in DB) to Lucide React icon components.
 * Used by Sidebar, ContinentalStats, and any component that renders domain icons dynamically.
 */
const ICON_MAP: Record<string, LucideIcon> = {
  HeartPulse,
  Wheat,
  Fish,
  TrendingUp,
  PawPrint,
  Bug,
  Landmark,
  CloudSun,
  BookOpen,
  Layers,
  ShieldCheck,
  Syringe,
  Globe2,
  Leaf,
  ClipboardCheck,
  BarChart3,
  Building2,
  TreePine,
  Cloud,
  Activity,
  Microscope,
  Stethoscope,
  FlaskConical,
  MapPin,
  Shield,
  Scale,
  Truck,
  Anchor,
  Bird,
  Sprout,
  Sun,
  Thermometer,
  Droplets,
  GraduationCap,
  FileText,
  Database,
  Settings,
  Globe,
  Heart,
  Zap,
  Target,
  Award,
  BriefcaseMedical,
};

/** Resolve an icon name string to a Lucide component. Falls back to Layers. */
export function resolveIcon(name: string | undefined | null): LucideIcon {
  if (!name) return Layers;
  return ICON_MAP[name] ?? Layers;
}
